# Generated by Django 6.0.6 on 2026-06-16 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_groups_customuser_user_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Платёж", "verbose_name_plural": "Платежи"},
        ),
    ]
