# Generated by Django 6.0.6 on 2026-07-03 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_customuser_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(2026, 7, 3, 9, 43, 57, 580443, tzinfo=datetime.timezone.utc),
                verbose_name="Дата последнего входа",
            ),
            preserve_default=False,
        ),
    ]
