# Generated by Django 6.0.6 on 2026-06-10 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Введите название курса", max_length=100, verbose_name="Название"),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение",
                        null=True,
                        upload_to="image_course/",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Введите описание курса", null=True, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Введите название урока", max_length=200, verbose_name="Название"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Введите описание урока", null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение",
                        null=True,
                        upload_to="image_lesson/",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "url_video",
                    models.TextField(
                        blank=True, help_text="Вставьте ссылку на видео", null=True, verbose_name="Ссылка на видео"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Выберете курс",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materials.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
