# Generated by Django 6.0.6 on 2026-06-15 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                help_text="Выберете курс",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Курс",
                to="materials.course",
                verbose_name="Курс",
            ),
        ),
    ]
