# Generated by Django 6.0.6 on 2026-06-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(default=0, help_text="Введите стоимость курса", verbose_name="Цена"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.PositiveIntegerField(default=0, help_text="Введите стоимость урока", verbose_name="Цена"),
        ),
    ]
